### ISSUE TITLE
Upgrade for Joi 16

### ISSUE THREAD

**Issue by chris48s** [dszakallas/joi-extension-semver#12]
As noted in https://github.com/hapijs/joi/issues/2037

> The entire extension system has been replaced with a new framework that is now at the core of the entire type system. Every built-in type is just an extension of the base type. Everything the built-in types can do is now available to extensions.

:cloud_with_rain: Bad news: This plugin needs a substantial rewrite to bring it up to date for Joi 16.

:sun_with_face: Good news: I made a start on this over the weekend. I've got a bit more to do, but its nearly there.. I'll finish it off, write up some notes and submit a PR in the week.

**Comment by paulmelnikow** [comment]
Woohoo! Thanks Chris!

**Comment by paulmelnikow** [comment]
Released as 4.0.0: https://www.npmjs.com/package/joi-extension-semver 🚀
