### ISSUE TITLE
Add types for Typescript

### ISSUE THREAD

**Issue by ealbuquerque** [dszakallas/joi-extension-semver#17]
# Description

Add typescript types to this library.
Preferably in the form of a built in .d.ts file or otherwise as a separate @types/joi-extension-semver package.

**Comment by dszakallas** [comment]
I am completely new to TypeScript. Is including TypeScript definitions in the repo the conventional way to package TypeScript definition for libraries? I know that in case of Flow, there's a separate https://github.com/flow-typed/flow-typed repository to keep them centralized.

**Comment by paulmelnikow** [comment]
There is a way to do that: https://github.com/DefinitelyTyped/DefinitelyTyped

However keeping them in the repo makes it more likely that they are kept up to date with API changes, and makes them easier for consumers to obtain and version, too. This is how we handle it for Nock. There's tooling we can use to verify the types, as well.

**Comment by dszakallas** [comment]
I see. No objections on my part, then. Given the popularity of TypeScript, this can be a useful addition.

**Comment by ealbuquerque** [comment]
I agree 100% with @paulmelnikow 

For compatibility reasons, I prefer that the types are within the project.
