### ISSUE TITLE
Incompatibility with @hapi/joi@15

### ISSUE THREAD

**Issue by deyvsh** [dszakallas/joi-extension-semver#2]
Hi, thanks very much for sharing your code - it's really useful!

I just tried an upgrade to latest major joi version (@hapi/joi@15) and now this line:

`JoiWithSemver = Joi.extend(require("joi-extension-semver"));`

throws this exception:

`"base" must be an instance of "Joi object"`

I'm in a rush right now but wanted to leave a warning in case anyone else hits the same problem. If I get a chance to research more I'll update this issue.

**Comment by sidjai** [comment]
Yep get the same error when updated to joi 15

**Comment by dszakallas** [comment]
Yikes! I sure could use a helping hand with this, I haven't developed in nodejs for a while.

**Comment by paulmelnikow** [comment]
@dszakallas Would you mind adding me and/or @chris48s to the repo and the npm project? Speaking for myself at least, I can say I'd be happy to maintain this. Chris and I work together on https://shields.io/.

**Comment by paulmelnikow** [comment]
Also if you'd prefer a pull request we could go that route!

**Comment by dszakallas** [comment]
Thanks @paulmelnikow for the help. I'll add you as maintainer in a sec.

**Comment by paulmelnikow** [comment]
Thanks! We're getting this going. Should have the release ready momentarily.

This is my account on npmjs: https://www.npmjs.com/~paulmelnikow

**Comment by paulmelnikow** [comment]
Ready to publish!

**Comment by paulmelnikow** [comment]
Hi @dszakallas, would you mind giving me publish access so I can wrap this up? Thanks!

**Comment by dszakallas** [comment]
@paulmelnikow I added you right now.

**Comment by paulmelnikow** [comment]
Published! https://www.npmjs.com/package/joi-extension-semver 🚀 

Thanks!
